Ideas:  [ { id: '20',
     offer_id: '4668',
     element_id: '19',
     text: 'Approved as Influencer',
     states: [ [Object], [Object] ] } ]
Ideas:  [ { id: '21',
     offer_id: '4669',
     element_id: '20',
     text: 'Approved As Influencer (second account)',
     states: [ [Object], [Object] ] } ]
Ideas:  [ { id: '22',
     offer_id: '4670',
     element_id: '21',
     text: 'Influencer Approved',
     states: [ [Object] ] } ]

# -------- STATES OBJECT ----------
States:  [ { id: '26',
     actor: null,
     actor_type: 'internal',
     status: 'approved',
     creator: '1',
     reference_type: 'offer-concept-idea',
     reference_id: '20',
     created: 1477367453,
     comment:
      { id: '74',
        author_id: '1',
        scribe_id: null,
        poster_type: null,
        text: 'Approved as campaign manager',
        reference_type: 'state',
        reference_id: '26',
        created: 1477367453 } },
   { id: '27',
     actor: null,
     actor_type: 'external',
     status: 'approved',
     creator: '1',
     reference_type: 'offer-concept-idea',
     reference_id: '20',
     created: 1477372515,
     comment:
      { id: '75',
        author_id: '1',
        scribe_id: null,
        poster_type: null,
        text: 'Approved in final step',
        reference_type: 'state',
        reference_id: '27',
        created: 1477372515 } } ]
