{
  campaign_offers: [
  {
      id: "4661",
      parent_id: null,
      is_scheduled: 0,
      is_interested: 1,
      terms_accepted: 1,
      post_attempted: 0,
      post_id: null,
      post_confirmed: 0,
      scheduled_time: null,
      is_schedule_reserved: 0,
      is_schedule_time_locked: 0,
      character_count: "0",
      sent: 0,
      campaign_offer_status_id: "1",
      created: 1476978572,
      updated: 1476978592,
      deleted: null,
      network_slug: "facebook",
      network: "Facebook",
      campaign: {...},
      bitly: null,
      twitter_card: null,
      terms: null,
      creator: {...},
      affiliate: {...},
      social_account: {...},
      price: {...},
      header: null,
      copy: null,
      media: {...},
      type: {...},
      forward_url: null,
      offer_concepts: [...],
      internal_status: "approved",
      external_status: "pending"
  }
  ],
  count: 1
}
