{id: "537", campaign_group_id: null, date_created: 1476978452, date_updated: 1476978549,…}
  bio_link_destination:null
  bitly:null
  campaign_content_concept_count:"0"
  campaign_group_id:null
  closed:0
  copy:null
  copy_change_required:0
  date_created:1476978452
  date_updated:1476978549
  demographic_gender:null
  demographic_location_match:null
  demographic_max_age:null
  demographic_min_age:null
  demographic_race:null
  demographic_rating:null
  description:"Test"
  disclosure:null
  header:null
  ibm_watson:0
  ibm_watson_trait_count:0
  id:"537"
  instructions:null
  invalid_change_request_count:0
  is_blessed:0
  is_scheduled:0
  keyhole:null
  legal_count:0
  manager_count:0
  master_list:null
  master_list_id:null
  media:null
  media_change_required:0
  network_name:"Facebook"
  network_slug:"facebook"
  offer_count:"1" # IS THIS IT? LOOK-HERE-PATRICK / NOT IT
  offer_end_date:1477496809
  offer_start_date:1476978409
  owner: {id: "1364", username: "jessmajess", name_first: "jessica", name_last: "maciejewski"}
  pending_brand_approval:0
  pending_campaign_manager_approval:0
  pending_change_request_count:0
  permission_level:65535
  required_post_duration:604800
  requirements:null
  run_end_date:1476978452
  run_start_date:1476978452
  slogan:"Test"
  stats_count:0
  terms:null
  terms_required:0
  title:"Best Test is Best"
  twitter_card:null
